# Site settings
title: RKLAB
email: riccardo.pasianotto@gmail.com
description: "Rklab è il blog nel quale puoi far crescere le tue potenzialità di web developer o di web designer. Segui i post e i video sul canale youtube di <strong>RKLAB</strong>. "
baseurl: ""
url: "http://www.rklab.it"

# Build settings
markdown: kramdown
permalink: pretty
sass: 
  sass_dir: assets/css/
port: 5000